spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            scope:
              - email
          kakao:
        provider:
          naver:
          kakao:


jwt:
  header: 
  token-validity-in-seconds: 8640
