spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: "naver"
            client-id: "nCrbIrdSiD7FmCCn_mcT"
            client-secret: "XU2OIYfue2"
            redirect-uri: "https://www.fitwith.net/login/callback/naver"
            authorization-grant-type: "authorization_code"
            scope:
              - email
          kakao:
            client-id: "8c49bcab44c609d5e2653edc2f56db26"
            client-secret: "URJlNPO30yqoTSTHHWfZCHgVrdgyi8KM"
            redirect-uri: "https://www.fitwith.net/login/callback/kakao"
            authorization-grant-type: "authorization_code"
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-name-attribute: "response"
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"


jwt:
  header: Authorization
  secret: a2xqLXByb2plY3QtZm9yLXVuaWNvcm4tbXVzdC1iZS11bmljb3Ju
  token-validity-in-seconds: 8640